name: Deploy to Surge

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build and Deploy
      run: |
        # Configurar Surge.sh
        npm install --global surge
        surge token 412da3aff00fce0db6dd131429c4e791

        # Desplegar en Surge.sh
        surge --project ./ --domain alexhaber_devops.surge.sh 
